# Gráficos Básicos no R {#graph_base}

<script src=https://cdn.datacamp.com/datacamp-light-latest.min.js></script>

Parte importante na ánalise de dados, desenvolvimento de modelos e interpretação de dados é o uso de ferramentas de visualização. Os gráficos são ferramentas poderosas que, em geral, auxilia o analista de dados a entender melhor conceitos e "extrair" informações de forma facilitada quando comparado a versão tabular.

## Histórico

As primeiras versões públicas do R apresentavam um grande diferencial em relação aos outros softwares de análise de dados da época (início 1990) que era a flexibilidade de ajustes e formatos. Esta facilidade e poder de ajustar/alterar todos os itens de um gráfico, aliados a facilidade de codificar modelos de forma facilitada, compoem os principais tópicos do sucesso da ferramenta no que se refere ao seu uso como software de análise de dados e computação científica.

Ao se instalar o R pela primeira vez, o mesmo oferece um conjunto de funcinalidades básicas e muitas outras obitidas por meio de plugins - que são chamadas de _library_ (bibliotecas). Em relação aos gráficos nos temos as seguinte opções (lista não exasustiva):

## Base (_default_)

Gráficos disponibilidados em toda instalação do R:

  - `r hist`
  - `r boxplot`
  - `r plot`
  - density plot (`r plot(density(.))`)

## Lattice (_lattice_)

Gráficos mais elaborados, desenvolvidos no Bell Labs (AT&T / Lucent) e bastante usando no software *S* (antecessor do _R_). Para obter mais informações, tutoriais e alguns exemplos, veja [Lattice Home](http://lattice.r-forge.r-project.org/index.php).

Alguns exemplos de gráficos:

  - Histogram;
  - BWPlot (Box-Whisker);
  - XYPlot;
  
A Lattice, trabalha o conceito de painéis de gráficos (panel e prepanel).  

## GGPlot2 (_ggplot2_)

Gráficos elaborados, criado a partir do conceito de "Gramática de Gráficos" e desenvolvido na Universidade de IOWA por Hadley Wickham, durante o seu Doutorado. 

A GGPlot é a ferramenta mais utilizada atualmente para criar gráficos no R e o tecnica de gramática de gráficos e utilizada em outras ferramentas (Principalmente Javascript) de visualização de dados. Para mais informações, documentação, tutoriais e exemplos, veja em [GGplot2 Home](http://ggplot2.org/).

Alguns exemplos de gráficos:

  - Linhas;
  - Curvas de ajuste (linear e não-linear);
  - Pontos;
  - Paineis;
  
A GGPlot, trabalha o conceito de camadas de gráficos (layers).   
